export const SENDING_REQUEST = 'SENDING_REQUEST';
export const REQUEST_ERROR = 'REQUEST_ERROR';

export const GET_EVENT_SELF = 'GET_EVENT_SELF';
export const SET_EVENT_SELF = 'SET_EVENT_SELF';

export const POST_LOGIN = 'POST_LOGIN';
export const POST_LOGOUT = 'POST_LOGOUT';
export const SEND_VERIFICATION = 'SEND_VERIFICATION';
export const SET_USER = 'SET_USER';
